services:
  node-server:
      build: .
      ports:
        - 3000:3000
      command: npm start
      develop: 
        watch:
          - action: sync
            path: ./src      
            target: /app/src              
  safer_gambling_db:
    image: mysql:latest
    ports: 
      - 3306:3306
    expose:
      - 3306
    restart: always    
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"   
    environment:      
      MYSQL_ROOT_PASSWORD: admin  
      MYSQL_DATABASE: gamblers    
    command: --init-file /docker-entrypoint-initdb.d/init.sql    