services:
  node-server:
      build: .
      ports:
        - 3000:3000
      command: npm start
      develop: 
        watch:
          - action: sync
            path: ./src      
            target: /app/src              
  safer_gambling_db:
    image: mysql:latest
    ports: 
      - 3307:3306
    expose:
      - 3307
    restart: always    
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    # command: --init-file /var/lib/mysql/init.sql
    environment:      
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gamblers
      MYSQL_USER: someOne
      MYSQL_PASSWORD: password